export const travelPlaces = [
    { id: 1, value: "Colombo" },
    { id: 2, value: "Kandy" },
    { id: 3, value: "Galle" },
    { id: 4, value: "Sigiriya" },
    { id: 5, value: "Anuradhapura" },
    { id: 6, value: "Polonnaruwa" },
    { id: 7, value: "Nuwara Eliya" },
    { id: 8, value: "Ella" },
    { id: 9, value: "Mirissa" },
    { id: 10, value: "Unawatuna" },
    { id: 11, value: "Bentota" },
    { id: 12, value: "Negombo" },
    { id: 13, value: "Trincomalee" },
    { id: 14, value: "Jaffna" },
    { id: 15, value: "Dambulla" },
    { id: 16, value: "Yala National Park" },
    { id: 17, value: "Wilpattu National Park" },
    { id: 18, value: "Adam's Peak" },
    { id: 19, value: "Hikkaduwa" },
    { id: 20, value: "Arugam Bay" },
    { id: 21, value: "Pasikuda" },
    { id: 22, value: "Batticaloa" },
    { id: 23, value: "Kitulgala" },
    { id: 24, value: "Ratnapura" },
    { id: 25, value: "Sinharaja Forest Reserve" },
    { id: 26, value: "Udawalawe National Park" },
    { id: 27, value: "Minneriya National Park" },
    { id: 28, value: "Pinnawala Elephant Orphanage" },
    { id: 29, value: "Kataragama" },
    { id: 30, value: "Tangalle" },
    { id: 31, value: "Kalpitiya" },
    { id: 32, value: "Nilaveli" },
    { id: 33, value: "Dikwella" },
    { id: 34, value: "Weligama" },
    { id: 35, value: "Horton Plains" },
    { id: 36, value: "Knuckles Mountain Range" },
    { id: 37, value: "Puttalam" },
    { id: 38, value: "Mannar" },
    { id: 39, value: "Ambalangoda" },
    { id: 40, value: "Beruwala" }
];