export const travelPlaces = [
    { id: 1, value: "Colombo" },
    { id: 2, value: "Kandy" },
    { id: 3, value: "Galle" },
    { id: 4, value: "Sigiriya" },
    { id: 5, value: "Anuradhapura" },
    { id: 6, value: "Polonnaruwa" },
    { id: 7, value: "Nuwara Eliya" },
    { id: 8, value: "Ella" },
    { id: 9, value: "Mirissa" },
    { id: 10, value: "Unawatuna" },
    { id: 11, value: "Bentota" },
    { id: 12, value: "Negombo" },
    { id: 13, value: "Trincomalee" },
    { id: 14, value: "Jaffna" },
    { id: 15, value: "Dambulla" },
    { id: 16, value: "Yala National Park" },
    { id: 17, value: "Wilpattu National Park" },
    { id: 18, value: "Adam's Peak" },
    { id: 19, value: "Hikkaduwa" },
    { id: 20, value: "Arugam Bay" },
    { id: 21, value: "Pasikuda" },
    { id: 22, value: "Batticaloa" },
    { id: 23, value: "Kitulgala" },
    { id: 24, value: "Ratnapura" },
    { id: 25, value: "Sinharaja Forest Reserve" },
    { id: 26, value: "Udawalawe National Park" },
    { id: 27, value: "Minneriya National Park" },
    { id: 28, value: "Pinnawala Elephant Orphanage" },
    { id: 29, value: "Kataragama" },
    { id: 30, value: "Tangalle" },
    { id: 31, value: "Kalpitiya" },
    { id: 32, value: "Nilaveli" },
    { id: 33, value: "Dikwella" },
    { id: 34, value: "Weligama" },
    { id: 35, value: "Horton Plains" },
    { id: 36, value: "Knuckles Mountain Range" },
    { id: 37, value: "Puttalam" },
    { id: 38, value: "Mannar" },
    { id: 39, value: "Ambalangoda" },
    { id: 40, value: "Beruwala" }
];

export const hotelList = [
    {
        id: 1,
        name: "Shangri-La Colombo",
        location: "Colombo",
        rating: 4.8,
        pricePerNight: 180,
        image: "https://example.com/shangrila-colombo.jpg",
        amenities: ["Free Wi-Fi", "Pool", "Spa", "Gym", "Restaurant", "Parking"],
        type: "Luxury",
    },
    {
        id: 2,
        name: "Amaya Hills",
        location: "Kandy",
        rating: 4.5,
        pricePerNight: 120,
        image: "https://example.com/amaya-hills.jpg",
        amenities: ["Free Wi-Fi", "Pool", "Mountain View", "Parking"],
        type: "Resort",
    },
    {
        id: 3,
        name: "Galle Fort Hotel",
        location: "Galle",
        rating: 4.6,
        pricePerNight: 140,
        image: "https://example.com/galle-fort.jpg",
        amenities: ["Free Wi-Fi", "Historic Building", "Restaurant"],
        type: "Boutique",
    },
    {
        id: 4,
        name: "Jetwing Yala",
        location: "Yala National Park",
        rating: 4.7,
        pricePerNight: 200,
        image: "https://example.com/jetwing-yala.jpg",
        amenities: ["Beach Access", "Safari Packages", "Pool", "Restaurant"],
        type: "Eco-Resort",
    },
    {
        id: 5,
        name: "98 Acres Resort & Spa",
        location: "Ella",
        rating: 4.9,
        pricePerNight: 220,
        image: "https://example.com/98acres.jpg",
        amenities: ["Free Wi-Fi", "Spa", "Nature View", "Restaurant"],
        type: "Resort",
    },
    {
        id: 6,
        name: "Araliya Green Hills Hotel",
        location: "Nuwara Eliya",
        rating: 4.3,
        pricePerNight: 110,
        image: "https://example.com/araliya-green.jpg",
        amenities: ["Heated Pool", "Restaurant", "Garden", "Free Wi-Fi"],
        type: "Hotel",
    },
    {
        id: 7,
        name: "Trinco Blu by Cinnamon",
        location: "Trincomalee",
        rating: 4.4,
        pricePerNight: 130,
        image: "https://example.com/trinco-blu.jpg",
        amenities: ["Beach Access", "Free Wi-Fi", "Diving", "Restaurant"],
        type: "Resort",
    },
    {
        id: 8,
        name: "Anantaya Resort & Spa",
        location: "Chilaw",
        rating: 4.2,
        pricePerNight: 100,
        image: "https://example.com/anantaya.jpg",
        amenities: ["Pool", "Spa", "Free Wi-Fi", "Lake View"],
        type: "Luxury",
    },
    {
        id: 9,
        name: "Cinnamon Red",
        location: "Colombo",
        rating: 4.1,
        pricePerNight: 90,
        image: "https://example.com/cinnamon-red.jpg",
        amenities: ["Rooftop Pool", "Restaurant", "Free Wi-Fi", "City View"],
        type: "Hotel",
    },
    {
        id: 10,
        name: "Mandara Resort",
        location: "Mirissa",
        rating: 4.0,
        pricePerNight: 95,
        image: "https://example.com/mandara.jpg",
        amenities: ["Beach Access", "Pool", "Free Wi-Fi", "Restaurant"],
        type: "Beach Resort",
    }
];
